title: Katelyn Wyatt # your name (or website title) here
logo: "/images/Profile-Circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computer Science Undergraduate 
  <br><br>
  University of Notre Dame 
  <br><br>
  <a href="https://www.linkedin.com/in/katelyn-wyatt-b6385316b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-cayman
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
